#!/usr/bin/env bash
#
# generate-imports.sh
#
# One-time use. Emits `import` blocks for the permission sets and account
# assignments that already exist in AWS, so this stack can adopt them instead of
# trying to create them.
#
# Needed because these resources were originally created by the base repo. Once
# it has forgotten them, they exist in AWS but in no state file, and this stack
# has to import them.
#
# Run this LOCALLY and never commit the output. Import IDs contain real account
# IDs and permission set ARNs, and this repository is public. imports.tf is
# gitignored for that reason.
#
# Usage:
#   AWS_PROFILE=<management-account> scripts/generate-imports.sh > imports.tf
#   grep -c '^import {' imports.tf
#   terraform plan          # must show imports and NO creates or destroys
#   terraform apply && rm imports.tf
#
# Written for bash 3.2 so it runs on stock macOS: no associative arrays.
# Progress and totals go to stderr, so only HCL reaches stdout.

set -euo pipefail

REGION="${AWS_REGION:-us-west-2}"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

log() { printf '%s\n' "$*" >&2; }

###########################################################
# Discover the instance
###########################################################

INSTANCE_ARN="$(aws sso-admin list-instances --region "$REGION" \
  --query 'Instances[0].InstanceArn' --output text)"
IDENTITY_STORE_ID="$(aws sso-admin list-instances --region "$REGION" \
  --query 'Instances[0].IdentityStoreId' --output text)"

if [[ -z "$INSTANCE_ARN" || "$INSTANCE_ARN" == "None" ]]; then
  log "error: no Identity Center instance found in $REGION"
  exit 1
fi

MASTER_ACCOUNT_ID="$(aws organizations describe-organization \
  --query 'Organization.MasterAccountId' --output text)"

log "Instance:       $INSTANCE_ARN"
log "Identity store: $IDENTITY_STORE_ID"
log "Management:     $MASTER_ACCOUNT_ID"

###########################################################
# Lookup tables, as tab-separated files
###########################################################

# id <TAB> name. The management account maps to the reserved `management` alias
# instead of its real name, matching the merge() in lookups.tf.
aws organizations list-accounts \
  --query 'Accounts[].[Id,Name]' --output text > "$WORK_DIR/accounts"

# group id <TAB> display name
aws identitystore list-groups --region "$REGION" \
  --identity-store-id "$IDENTITY_STORE_ID" \
  --query 'Groups[].[GroupId,DisplayName]' --output text > "$WORK_DIR/groups"

# name <TAB> arn, one line per permission set
: > "$WORK_DIR/permsets"
aws sso-admin list-permission-sets --region "$REGION" \
  --instance-arn "$INSTANCE_ARN" --query 'PermissionSets[]' --output text \
  | tr '\t' '\n' | while read -r arn; do
      [[ -z "$arn" ]] && continue
      name="$(aws sso-admin describe-permission-set --region "$REGION" \
        --instance-arn "$INSTANCE_ARN" --permission-set-arn "$arn" \
        --query 'PermissionSet.Name' --output text)"
      printf '%s\t%s\n' "$name" "$arn" >> "$WORK_DIR/permsets"
    done

lookup_account() {
  if [[ "$1" == "$MASTER_ACCOUNT_ID" ]]; then
    printf 'management\n'
    return
  fi
  awk -F'\t' -v id="$1" '$1 == id { print $2; exit }' "$WORK_DIR/accounts"
}

lookup_group() {
  awk -F'\t' -v id="$1" '$1 == id { print $2; exit }' "$WORK_DIR/groups"
}

log "Permission sets: $(wc -l < "$WORK_DIR/permsets" | tr -d ' ')"

###########################################################
# Emit
###########################################################

echo "# Generated by scripts/generate-imports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# One-time adoption of resources created by the base repo."
echo "# Do not commit. Delete after the apply succeeds."
echo ""

while IFS=$'\t' read -r name arn; do
  [[ -z "$name" ]] && continue

  cat <<EOF
import {
  to = aws_ssoadmin_permission_set.this["${name}"]
  id = "${arn},${INSTANCE_ARN}"
}

import {
  to = aws_ssoadmin_permission_set_inline_policy.this["${name}"]
  id = "${arn},${INSTANCE_ARN}"
}

EOF

  # Only present when a managed policy is attached.
  managed="$(aws sso-admin list-managed-policies-in-permission-set \
    --region "$REGION" --instance-arn "$INSTANCE_ARN" \
    --permission-set-arn "$arn" \
    --query 'AttachedManagedPolicies[0].Arn' --output text 2>/dev/null || true)"

  if [[ -n "$managed" && "$managed" != "None" ]]; then
    cat <<EOF
import {
  to = aws_ssoadmin_managed_policy_attachment.this["${name}"]
  id = "${managed},${arn},${INSTANCE_ARN}"
}

EOF
  fi

  # Assignments, per account this set is provisioned into.
  aws sso-admin list-accounts-for-provisioned-permission-set \
    --region "$REGION" --instance-arn "$INSTANCE_ARN" \
    --permission-set-arn "$arn" \
    --query 'AccountIds[]' --output text | tr '\t' '\n' | while read -r account_id; do
      [[ -z "$account_id" ]] && continue

      account="$(lookup_account "$account_id")"
      if [[ -z "$account" ]]; then
        log "SKIPPED: cannot resolve account $account_id"
        continue
      fi

      aws sso-admin list-account-assignments --region "$REGION" \
        --instance-arn "$INSTANCE_ARN" --account-id "$account_id" \
        --permission-set-arn "$arn" \
        --query 'AccountAssignments[].[PrincipalId,PrincipalType]' \
        --output text | while IFS=$'\t' read -r principal_id principal_type; do
          [[ -z "$principal_id" ]] && continue
          [[ "$principal_type" != "GROUP" ]] && continue

          group="$(lookup_group "$principal_id")"
          if [[ -z "$group" ]]; then
            log "SKIPPED: cannot resolve group $principal_id"
            continue
          fi

          cat <<EOF
import {
  to = aws_ssoadmin_account_assignment.this["${account}-${group}-${name}"]
  id = "${principal_id},GROUP,${account_id},AWS_ACCOUNT,${arn},${INSTANCE_ARN}"
}

EOF
        done
    done
done < "$WORK_DIR/permsets"

log "Done. Verify with: grep -c '^import {' imports.tf"
